### ISSUE TITLE
**💲 Powershell commands for Getting Started**

### ISSUE THREAD

**Issue by MikeYeager** [tryphotino/tryphotino.github.io#7]
In Windows Powershell, the current way how commands are copied from the terminal, with line delimiters and "&&" doesn't work.

Find out what does work and copy that into the clipboard if the visitor uses Windows.

**Comment by majdisorder** [comment]
Also: the first command listed on the getting started page doesn't work. I'm refering to the command for installing the project templates. It's a bit annoying because` dotnet new` provides no feedback whatsoever. 

The command listed on nuget.org -using the version specifier- does the trick.

`dotnet new --install TryPhotino.VSCode.Project.Templates::1.1.0`

This might be a little off-putting for first time users, especially because it's the very first command on the getting started page   :-)

**Comment by MikeYeager** [comment]
Thank you for the input. We've not experienced the issue with having to include the version # in the command, though we've only tested with command prompt in Windows. We will test with PowerShell. According to NuGet, you should get the latest version if it's not specified. The && in the copied code were written for macOS and Linux. We will change it to use semicolon ';' if the browser detects Windows. Good catch! Cheers!

**Comment by MikeYeager** [comment]
Added a comment about Windows Powershell and changed -i parameter to install.
